<?php

declare(strict_types=1);

namespace Componenta\Profiler\Integration;

use ReflectionClass;
use ReflectionIntersectionType;
use ReflectionMethod;
use ReflectionNamedType;
use ReflectionParameter;
use ReflectionType;
use ReflectionUnionType;
use RuntimeException;

/**
 * Generates a profiling subclass for a given target and writes it to the
 * cache directory once; subsequent requests pick it up from disk / OPcache.
 *
 * Strategy: the generated class extends the target and overrides every
 * eligible public instance method with:
 *
 *     $s = self::$__profiler->span(self::$__label . '::method');
 *     try { return parent::method(...$args); } finally { $s->close(); }
 *
 * State is not duplicated - the delegator transplants parent properties from
 * the already-built target instance into the proxy via reflection. This is
 * why the class must be non-final and free of class-level defaults on
 * readonly properties (those would lock the slot before transplant can fill
 * it on new proxy instances).
 *
 * Methods that are static, final, abstract, magic, or by-reference on any
 * parameter are not overridden; calls to them bypass the profiler and run
 * on the parent unchanged.
 */
final class ClassProxyGenerator
{
    public function __construct(
        private readonly string $cacheDir,
    ) {}

    /**
     * @param class-string $target
     *
     * @return class-string
     */
    public function generate(string $target): string
    {
        $reflection = new ReflectionClass($target);

        $this->assertProxyable($reflection);

        [$proxyFqcn, $proxyShort] = $this->proxyName($reflection);
        $file = $this->cacheDir . '/' . $proxyShort . '.php';

        if (!class_exists($proxyFqcn, autoload: false)) {
            if (!is_file($file)) {
                $this->ensureCacheDir();
                $this->writeAtomic($file, $this->renderSource($reflection, $proxyShort));
            }

            require_once $file;
        }

        /** @var class-string $proxyFqcn */
        return $proxyFqcn;
    }

    /**
     * Proxy name bakes in the target source mtime so editing the target
     * between requests produces a fresh proxy class (old files stay in the
     * cache as tiny orphans - acceptable for a dev-only cache).
     *
     * @return array{0: class-string, 1: string}
     */
    private function proxyName(ReflectionClass $reflection): array
    {
        $file  = $reflection->getFileName();
        $mtime = $file !== false && is_file($file) ? (string) filemtime($file) : '0';
        $hash  = substr(hash('xxh128', $reflection->name . '|' . $mtime), 0, 12);
        $short = str_replace('\\', '_', $reflection->name) . '_' . $hash . 'Proxy';
        $fqcn  = 'Componenta\\Profiler\\Proxy\\Generated\\' . $short;

        /** @var class-string $fqcn */
        return [$fqcn, $short];
    }

    private function assertProxyable(ReflectionClass $reflection): void
    {
        if ($reflection->isFinal()) {
            throw new RuntimeException(
                "Cannot profile {$reflection->name}: class is final.",
            );
        }

        if ($reflection->isAbstract() || $reflection->isInterface() || $reflection->isTrait() || $reflection->isEnum()) {
            throw new RuntimeException(
                "Cannot profile {$reflection->name}: not a concrete class.",
            );
        }

        foreach ($reflection->getProperties() as $property) {
            if ($property->isReadOnly() && $property->hasDefaultValue()) {
                throw new RuntimeException(sprintf(
                    'Cannot profile %s: readonly property $%s has a class-level default ' .
                    'which would lock the slot before transplantation.',
                    $reflection->name,
                    $property->name,
                ));
            }
        }
    }

    private function renderSource(ReflectionClass $reflection, string $proxyShort): string
    {
        $overrides = [];

        foreach ($reflection->getMethods(ReflectionMethod::IS_PUBLIC) as $method) {
            if (!$this->isOverridable($method)) {
                continue;
            }

            $overrides[] = $this->renderMethod($method);
        }

        $parentFqcn = '\\' . $reflection->name;
        $overridesSource = implode("\n\n", $overrides);

        return <<<PHP
<?php

declare(strict_types=1);

namespace Componenta\\Profiler\\Proxy\\Generated;

/**
 * Auto-generated by Componenta\\Profiler - do not edit.
 * Target: {$reflection->name}
 */
final class {$proxyShort} extends {$parentFqcn}
{
    public static \\Componenta\\Profiler\\ProfilerInterface \$__profiler;
    public static string \$__label;

{$overridesSource}
}

PHP;
    }

    private function isOverridable(ReflectionMethod $method): bool
    {
        if ($method->isStatic() || $method->isFinal() || $method->isAbstract()) {
            return false;
        }

        if ($method->isConstructor() || $method->isDestructor()) {
            return false;
        }

        if (str_starts_with($method->name, '__')) {
            return false;
        }

        // self/static/parent change meaning when the method is redeclared on
        // the proxy subclass; rewriting them safely requires LSP analysis per
        // position. Skipping avoids spurious runtime type errors - covariant
        // builder-style methods bypass the profiler and run on the parent
        // unchanged, which is a minor but correct trade-off.
        if ($this->referencesRelativeType($method->getReturnType())) {
            return false;
        }

        foreach ($method->getParameters() as $parameter) {
            if ($parameter->isPassedByReference()) {
                return false;
            }

            if ($this->referencesRelativeType($parameter->getType())) {
                return false;
            }
        }

        return true;
    }

    private function referencesRelativeType(?ReflectionType $type): bool
    {
        if ($type === null) {
            return false;
        }

        if ($type instanceof ReflectionNamedType) {
            return in_array($type->getName(), ['self', 'static', 'parent'], true);
        }

        if ($type instanceof ReflectionUnionType || $type instanceof ReflectionIntersectionType) {
            foreach ($type->getTypes() as $inner) {
                if ($this->referencesRelativeType($inner)) {
                    return true;
                }
            }
        }

        return false;
    }

    private function renderMethod(ReflectionMethod $method): string
    {
        $params      = $method->getParameters();
        $paramList   = $this->renderParameters($params);
        $argList     = $this->renderArguments($params);
        $returnType  = $this->renderType($method->getReturnType());
        $returnClause = $returnType !== null ? ': ' . $returnType : '';

        $parentCall  = 'parent::' . $method->name . '(' . $argList . ')';
        $spanLabel   = 'self::$__label . \'::' . $method->name . '\'';

        $body = $this->renderMethodBody($method, $parentCall, $spanLabel);

        return <<<PHP
    public function {$method->name}({$paramList}){$returnClause}
    {
{$body}
    }
PHP;
    }

    private function renderMethodBody(ReflectionMethod $method, string $parentCall, string $spanLabel): string
    {
        $returnType = $method->getReturnType();
        $typeName   = $returnType instanceof ReflectionNamedType ? $returnType->getName() : null;

        $open  = "        \$__span = self::\$__profiler->span({$spanLabel});";
        $close = "            \$__span->close();";

        if ($typeName === 'void') {
            return <<<PHP
{$open}
        try {
            {$parentCall};
            return;
        } finally {
{$close}
        }
PHP;
        }

        if ($typeName === 'never') {
            return <<<PHP
{$open}
        try {
            {$parentCall};
        } finally {
{$close}
        }
PHP;
        }

        return <<<PHP
{$open}
        try {
            return {$parentCall};
        } finally {
{$close}
        }
PHP;
    }

    /**
     * @param array<ReflectionParameter> $params
     */
    private function renderParameters(array $params): string
    {
        $parts = [];

        foreach ($params as $param) {
            $type = $this->renderType($param->getType());
            $typePart = $type !== null ? $type . ' ' : '';
            $variadic = $param->isVariadic() ? '...' : '';
            $name = '$' . $param->name;

            $part = $typePart . $variadic . $name;

            if (!$param->isVariadic() && $param->isDefaultValueAvailable()) {
                $part .= ' = ' . $this->renderDefaultValue($param);
            }

            $parts[] = $part;
        }

        return implode(', ', $parts);
    }

    /**
     * @param array<ReflectionParameter> $params
     */
    private function renderArguments(array $params): string
    {
        $parts = [];

        foreach ($params as $param) {
            $parts[] = ($param->isVariadic() ? '...' : '') . '$' . $param->name;
        }

        return implode(', ', $parts);
    }

    private function renderType(?ReflectionType $type): ?string
    {
        if ($type === null) {
            return null;
        }

        if ($type instanceof ReflectionNamedType) {
            $name = $type->getName();
            $prefix = $type->allowsNull() && $name !== 'mixed' && $name !== 'null' ? '?' : '';

            return $prefix . $this->normalizeTypeName($name);
        }

        if ($type instanceof ReflectionUnionType) {
            return implode('|', array_map(
                fn (ReflectionType $t): string => $this->renderType($t) ?? '',
                $type->getTypes(),
            ));
        }

        if ($type instanceof ReflectionIntersectionType) {
            return implode('&', array_map(
                fn (ReflectionType $t): string => $this->renderType($t) ?? '',
                $type->getTypes(),
            ));
        }

        return (string) $type;
    }

    private function normalizeTypeName(string $name): string
    {
        $builtins = [
            'int', 'float', 'string', 'bool', 'array', 'object', 'mixed',
            'void', 'never', 'null', 'false', 'true', 'iterable', 'callable',
            'self', 'static', 'parent',
        ];

        if (in_array($name, $builtins, true)) {
            return $name;
        }

        return '\\' . ltrim($name, '\\');
    }

    private function renderDefaultValue(ReflectionParameter $param): string
    {
        if ($param->isDefaultValueConstant()) {
            $name = $param->getDefaultValueConstantName();

            if ($name !== null) {
                return $this->resolveConstantName($name, $param->getDeclaringClass());
            }
        }

        return var_export($param->getDefaultValue(), true);
    }

    /**
     * Resolve `self::X` / `parent::X` to absolute names, and emit global
     * constants / absolute class constants fully qualified so they don't
     * look up against the generated proxy's namespace.
     */
    private function resolveConstantName(string $name, ?ReflectionClass $declaring): string
    {
        if (str_starts_with($name, '\\')) {
            return $name;
        }

        $colon = strpos($name, '::');

        if ($colon === false) {
            return '\\' . $name;
        }

        $classPart    = substr($name, 0, $colon);
        $constantPart = substr($name, $colon);

        if ($declaring !== null) {
            $resolved = match (strtolower($classPart)) {
                'self', 'static' => '\\' . $declaring->name,
                'parent'         => $declaring->getParentClass() !== false
                    ? '\\' . $declaring->getParentClass()->name
                    : null,
                default          => null,
            };

            if ($resolved !== null) {
                return $resolved . $constantPart;
            }
        }

        return '\\' . $name;
    }

    private function ensureCacheDir(): void
    {
        if (is_dir($this->cacheDir)) {
            return;
        }

        if (!mkdir($this->cacheDir, 0o755, recursive: true) && !is_dir($this->cacheDir)) {
            throw new RuntimeException("Unable to create profiler cache directory: {$this->cacheDir}");
        }
    }

    private function writeAtomic(string $path, string $contents): void
    {
        $tmp = $path . '.' . bin2hex(random_bytes(4)) . '.tmp';

        if (file_put_contents($tmp, $contents) === false) {
            throw new RuntimeException("Unable to write profiler proxy: {$path}");
        }

        if (!rename($tmp, $path)) {
            @unlink($tmp);

            throw new RuntimeException("Unable to finalise profiler proxy: {$path}");
        }
    }
}
